### ISSUE TITLE
圈 X  moodji 1.2.6.1 版本好像失效了

### ISSUE THREAD

**Issue by wow-doubao** [qwe1187292926/MyQuantumultXRewrite#1]
日志
🔔Moodji获取全皮肤 v1.0, 开始!
2024/03/23 19:00:46:044  <error>      [JS Console]: [Exception]: null is not an object (evaluating 'i.length').
2024/03/23 19:00:46:045  <error>      [JS Console]: Exception null is not an object (evaluating 'i.length'), https://raw.githubusercontent.com/qwe1187292926/MyQuantumultXRewrite/main/Moodji/skin.min.js
2024/03/23 19:00:46:047  <error>      [JS Console]: [Exception]: null is not an object (evaluating 'i.length').
2024/03/23 19:00:46:051  <error>      [JS Console]: Exception null is not an object (evaluating 'i.length'), https://raw.githubusercontent.com/qwe1187292926/MyQuantumultXRewrite/main/Moodji/skin.min.js

**Comment by qwe1187292926** [comment]
压缩脚本看不出来问题在哪，用这个脚本再试一次看看日志？
https://raw.githubusercontent.com/qwe1187292926/MyQuantumultXRewrite/feture-moodji-20240302/Moodji/skin.js

**Comment by qwe1187292926** [comment]
之前有成功过吗，还是更新了app就不行了

**Comment by wow-doubao** [comment]
感谢您的来信，查阅后我将以最快速度回复您，谢谢。

**Comment by wow-doubao** [comment]
首先  感谢作者的付出
我也是第一次用 moodji  顺便搜了下脚本  不知道之前的版本是否成功

日志
🔔Moodji获取全皮肤 v1.0, 开始!
2024/03/23 20:59:17:901  <console>    [JS Console]: 上次保存皮肤为空，开始获取皮肤信息
2024/03/23 20:59:17:903  <error>      [JS Console]: [Exception]: null is not an object (evaluating 'products.length').
2024/03/23 20:59:17:904  <error>      [JS Console]: Exception null is not an object (evaluating 'products.length'), https://raw.githubusercontent.com/qwe1187292926/MyQuantumultXRewrite/feture-moodji-20240302/Moodji/skin.js
2024/03/23 20:59:17:905  <console>    [JS Console]: savedSkinList->[undefined]
2024/03/23 20:59:17:909  <console>    [JS Console]: 上次保存皮肤为空，开始获取皮肤信息
2024/03/23 20:59:17:912  <error>      [JS Console]: [Exception]: null is not an object (evaluating 'products.length').
2024/03/23 20:59:17:914  <error>      [JS Console]: Exception null is not an object (evaluating 'products.length'), https://raw.githubusercontent.com/qwe1187292926/MyQuantumultXRewrite/feture-moodji-20240302/Moodji/skin.js

**Comment by wow-doubao** [comment]
是不是得开 vip 后才能用

**Comment by qwe1187292926** [comment]
应该不用vip也可以，更新下脚本再试试

**Comment by wow-doubao** [comment]
看起来 还是不行

🔔Moodji获取全皮肤 v1.0, 开始!
2024/03/23 21:57:58:716  <console>    [JS Console]: 
🔔Moodji获取全皮肤 v1.0, 开始!
2024/03/23 21:57:58:719  <console>    [JS Console]: savedSkinList->[undefined]
2024/03/23 21:57:58:721  <console>    [JS Console]: 上次保存皮肤为空，开始获取皮肤信息
2024/03/23 21:57:58:721  <console>    [JS Console]: savedSkinList->[undefined]
2024/03/23 21:57:58:722  <error>      [JS Console]: [Exception]: null is not an object (evaluating 'products.length').
2024/03/23 21:57:58:723  <console>    [JS Console]: 上次保存皮肤为空，开始获取皮肤信息
2024/03/23 21:57:58:723  <error>      [JS Console]: Exception null is not an object (evaluating 'products.length'), https://raw.githubusercontent.com/qwe1187292926/MyQuantumultXRewrite/feture-moodji-20240302/Moodji/skin.js
2024/03/23 21:57:58:726  <error>      [JS Console]: [Exception]: null is not an object (evaluating 'products.length').
2024/03/23 21:57:58:727  <error>      [JS Console]: Exception null is not an object (evaluating 'products.length'), https://raw.githubusercontent.com/qwe1187292926/MyQuantumultXRewrite/feture-moodji-20240302/Moodji/skin.js

**Comment by qwe1187292926** [comment]
不好意思，更新脚本再试试吧😂

**Comment by wow-doubao** [comment]
通读大佬代码后  products = body.products || [];   改成这就好了

**Comment by qwe1187292926** [comment]
献丑了hhh，按你说的提交了，可以再试试。我也是个萌新 :)
